# mediawiki_playbook_with_vars.yml

- hosts: test
  tasks:
    - name: Include Variables
      include_vars:
        file: vars.yml
    
    - name: Install Required Packages
      become: yes
      apt:
        pkg:
          - apache2
          - mysql-server
          - php 
          - php-mysql
          - libapache2-mod-php
          - php-xml
          - php-mbstring
          - php-intl
          - python2-pip
        state: present
        update_cache: yes

    - name: Download Media Wiki Tar 
      get_url:
        url: "{{ mw_url }}"
        dest: "{{ temp_dest }}"

    - name: Create / mediawiki Directory
      become: yes
      file: 
        path: "{{ mw_path }}"
        state: directory

    - name: Extract Media Wiki Tar 
      become: yes
      unarchive:
        src: /tmp/mediawiki-1.37.1.tar.gz
        dest: "{{ mw_path }}"
        remote_src: yes
 
    - name: SymLink for MediaWiki
      become: yes
      file: 
        src: /var
        dest: /va
        state: link
 
    - name: Update Apache2 Enabled Sites 
      become: yes
      replace: 
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: 'DocumentRoot \/var\/html$'
        replace: 'DocumentRoot /var/www/html/mediawiki'

    - name: Restart Apache2 Service 
      become: yes
      Service:
        name: apache2
        state: restarted
        enabled: yes

# SQL commands require community.msql to be installe:
# ansible-galaxy collection install community.mysql

    - name: Pip Pre-Reqs for SQL 
      become: yes
      pip:
        name: PyMySQL
    
    - name: Enable MySQL
      become: yes
      service: 
        name: mysql
        state: started
        enabled: yes

    - name: Create database for MediaWiki
      become: yes
      become_user: root
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ db_name }}"
        state: present

    -name: Create MediaWiki DB user 
      become: yes
      become_user: root 
      community.mysql.mysql_user: 
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present 
        name: "{{ db_user_name }}"
        password: "{{ db_user_password }}"
        priv:
          'mediawiki.*:ALL,GRANT'
        
 
 
    
 
    